baseURL = ""
languageCode = "en"
title = "arki.vet"
theme = "aliquote"
paginate = 10
enableRobotsTXT = true

# disable
pygmentsUseClasses = true
pygmentsStyle = "bw"
pygmentsCodefences = true
pygmentsCodefencesGuessSyntax = true

[blackfriday]
    fractions = false

[markup.goldmark.renderer]
    unsafe= true

[sitemap]
    changefreq = "weekly"
    priority = 0.5
    filename = "sitemap.xml"

[author]
  name = "joafr"

summaryLength = 20

[params]
	subtitle = "— där jag samlar mina intryck av sånt som gör avtryck"
	mainSections = ["tweet"]
	featherIconsCDN = true
	wc = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

[[menu.main]]
name = "Texter"
url = "/post"
weight = 1

[[menu.main]]
name = "Nu"
url = "/now"
weight = 50

[[params.social]]
name = "Sök"
icon = "search"
url = "/search"

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/jfrogren"

[[params.social]]
name = "Email"
icon = "mail"
url = "mailto:joakim@frogren.se"

[[params.social]]
name = "RSS"
icon = "rss"
url = "/index.xml"

[taxonomies]
   tag = "tags"
   category = "categories"
