baseURL = "https://www.frogren.se/"
languageCode = "sv"
title = "frogren.se"
theme = "ezhil"
paginate = 5

copyright = "© Joakim Frögren"

pygmentsstyle = "solarized-dark"
pygmentscodefeces = true
pygmentscodefencesguesssyntax = true

googleAnalytics = "UA-123-45"
# disqusShortname = "ezhil-demo"

summaryLength = 20

[params]
	subtitle = "— där jag samlar mina intryck av sånt som gör avtryck"
	# disableDisqusTypes = ["page"]
	featherIconsCDN = true
	mode = "auto" # "dark", "auto", "light"
	# customCSS = "css/custom.css"  # Custom CSS applied to default styles.
	# customDarkCSS = "css/custom-dark.css"  # Custom styles applied to dark mode css.
	# customJS = ["https://code.jquery.com/jquery-3.4.1.js", "js/custom1.js"]  # Custom JS scripts.

[[menu.main]]
name = "Om"
url = "/about"
weight = 1

[[menu.main]]
name = "Noteringar"
url = "/posts"
weight = 2

[[menu.main]]
name = "Texter"
url = "/about"
weight = 3

[[menu.main]]
name = "Taggar"
url = "/tags"
weight = 4

[[menu.main]]
name = "Nu"
url = "/about"
weight = 5

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/jfrogren"

[[params.social]]
name = "RSS"
icon = "rss"
url = "/index.xml"

[taxonomies]
   tag = "tags"
